# ActionsStrator Configuration File
# -----------------------------------------------------------------------------------------------------------
# MineStrator API Key
# You can generate one on your MineStrator panel
# 🔗 Link: https://minestrator.com/my/account?section=api
api_key: "YOUR_API_KEY_HERE"

# Server ID
# The ID of the server you want to control (you can find this in your server URL)
# 🔗 Link: https://minestrator.com/my/dashboard
server_id: "YOUR_SERVER_ID_HERE"

# -----------------------------------------------------------------------------------------------------------
