name: ActionsStrator
version: '${version}'
main: fr.heavencube.actionsstrator.ActionsStrator
api-version: '1.21'
description: A Paper plugin that uses the MineStrator API to manage the server.
authors:
- Noltox
permissions:
  actionsstrator.restart:
    description: Allows using /msrestart
    default: op
  actionsstrator.stop:
    description: Allows using /msstop
    default: op
